[package]
name = "nanoid-dictionary"
version = "0.1.0"
edition = "2018"
license = "MIT"
description = "Set of dictionaries for nanoid"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
