[package]
name = "nanoid-dictionary"
version = "0.4.1"
edition = "2018"
repository = "https://gitlab.com/imp/nanoid-dictionary-rs"
license = "MIT"
description = "Set of dictionaries for nanoid"

[dev-dependencies]
nanoid = "0.4"
