[package]
name = "nanoid-dictionary"
version = "0.4.2"
edition = "2021"
repository = "https://gitlab.com/imp/nanoid-dictionary-rs"
license = "MIT"
description = "Popular alphabets for use with nanoid"

[dev-dependencies]
nanoid = "0.4"
